export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Intro } from './Intro'
export { default as Experience } from './Experience'
export { default as Skills } from './Skills'
export { default as Wormseye } from './WormsEye'